# Reference: https://github.com/cli/cli/blob/v2.32.1/.goreleaser.yml

project_name: outcli

release:
  draft: true
  replace_existing_draft: true
  name_template: "{{ .Tag }}"

before:
  hooks:
    - go mod tidy

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    main: ./cmd/outcli
    ldflags:
      - -s -w -X github.com/ioki-mobility/go-outline/internal/common.Version={{ .Tag }}

  - id: linux
    goos: [linux]
    goarch: [amd64]
    main: ./cmd/outcli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/ioki-mobility/go-outline/internal/common.Version={{ .Tag }}

archives:
  - id: linux-archive
    builds: [linux]
    name_template: "outcli_{{ .Tag }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true

  - id: macos-archive
    builds: [macos]
    name_template: "outcli_{{ .Tag }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
