name: Checks

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cli-docs-up-to-date:
    name: cli-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache: false
      - name: Refresh CLI docs
        run: go run internal/cli-docgen.go

      - name: Verify whether CLI documentation is up-to-date
        run: git diff --exit-code

  # Reference: https://github.com/golangci/golangci-lint-action
  golangci-lint:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.53.3

  go-test:
    name: testing
    runs-on: ubuntu-latest 
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.2'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Test
        run: go test -v -race -cover ./...
