name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Can be added as needed
      # - name: Login to Docker Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ioki/outline-cli:latest
          platforms: linux/amd64

      - name: Get version from Git tag
        id: version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build and Push Docker Image (versioned)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ioki/outline-cli:${{ steps.version.outputs.VERSION }}
          platforms: linux/amd64
