name: Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildGitHubPages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.124.1' 

      - name: Prepare and build website
        run: |
          hugo new site outclidocs
          cd outclidocs
          hugo mod init github.com/ioki-mobility/go-outline
          hugo mod get github.com/alex-shpak/hugo-book@e104a11f42fbd069aa15606c5f01631b07d7528c # This is tag `v10`
          cp ../cmd/outcli/docs/website/hugo.toml hugo.toml
          cp ../cmd/outcli/docs/website/_index.md content/_index.md
          mkdir content/docs
          cp ../cmd/outcli/docs/*.md content/docs
          hugo

      - name: Upload artifact to GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./outclidocs/public

  deployGitHubPages:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: buildGitHubPages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
