name: Website

on:
  push:
    branches:
      - main

jobs:
  buildGitHubPages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Hugo
        run: sudo apt install hugo

      - name: Prepare and build website
        run: |
          hugo new site outclidocs
          cd outclidocs
          hugo mod init github.com/ioki-mobility/go-outline
          cp ../cmd/outcli/docs/website/config.toml config.toml
          cp ../cmd/outcli/docs/website/_index.md content/_index.md
          mkdir content/docs
          cp ../cmd/outcli/docs/*.md content/docs
          hugo

      - name: Upload artifact to GitHub pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./outclidocs/public

  deployGitHubPages:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: buildGitHubPages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
